-- 005_create_mistake_garden.sql
-- SUPERSEDED BY 001_initial_schema.sql
-- This migration is intentionally empty. The mistakes table is now created
-- by 001_initial_schema.sql with a more comprehensive schema (source tracking,
-- spaced repetition fields, review counts).
